In [2]:
import pandas as pd

In [27]:
sd = pd.DataFrame({

    "Salary": [1000,2000,3000,5000,7000,8000,9000,12000, 26000]
})
sd

   Salary
0    1000
1    2000
2    3000
3    5000
4    7000
5    8000
6    9000
7   12000
8   26000

In [28]:
median = sd["Salary"].quantile(0.5)
median

np.float64(7000.0)

In [29]:
q1 = sd["Salary"].quantile(0.25)
q1

np.float64(3000.0)

In [30]:
q3 = sd["Salary"].quantile(0.75)
q3

np.float64(9000.0)

In [31]:
#IQR
iqr = q3-q1
iqr

np.float64(6000.0)

In [32]:
lower_bound = q1-(1.5*iqr)
lower_bound

np.float64(-6000.0)

In [33]:
upper_bound = q3+(1.5*iqr)
upper_bound

np.float64(18000.0)

In [34]:
outliers = sd[(sd["Salary"]< lower_bound)|(sd["Salary"]> upper_bound)]
outliers

   Salary
8   26000